/**
 * Canonical Error Category Taxonomy (DOM-03, DOM-06)
 * Strictly derived from Step 6D Section 3 & Step 6F.
 */

export enum ErrorCategory {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
  DOMAIN_INVARIANT_ERROR = 'DOMAIN_INVARIANT_ERROR',
  CONFLICT_ERROR = 'CONFLICT_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  INTEGRATION_ERROR = 'INTEGRATION_ERROR',
  RATE_LIMIT_ERROR = 'RATE_LIMIT_ERROR',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}
